function distance = getDistance( Route )
global numberOfCity cityCordinates;
distance=0;
for i=1:numberOfCity-1
    distance=distance+sqrt(...
       (cityCordinates(Route(i),1)-cityCordinates(Route(i+1),1))^2+ ...
       (cityCordinates(Route(i),2)-cityCordinates(Route(i+1),2))^2  ...
   );
distance=distance+sqrt(...
       (cityCordinates(Route(1),1)-cityCordinates(Route(numberOfCity),1))^2+ ...
       (cityCordinates(Route(1),2)-cityCordinates(Route(numberOfCity),2))^2  ...
   );
end

